--The tables
CREATE TABLE login_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50),
    attempt_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20), -- 'SUCCESS' or 'FAILED'
    ip_address VARCHAR2(50)
);

CREATE TABLE security_alerts (
    alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50),
    failed_count NUMBER,
    alert_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    alert_message VARCHAR2(255),
    notify_email VARCHAR2(100)
);

--The Trigger 
CREATE OR REPLACE TRIGGER trg_check_suspicious_login
FOR INSERT ON login_audit
COMPOUND TRIGGER

    -- 1. Setup list to hold usernames
    TYPE t_user_list IS TABLE OF login_audit.username%TYPE;
    v_users_to_check t_user_list := t_user_list();
    
    v_failed_count NUMBER;
    v_limit CONSTANT NUMBER := 2; 

    -- 2. AFTER EACH ROW: Catch the username
    AFTER EACH ROW IS
    BEGIN
        IF :NEW.status = 'FAILED' THEN
            v_users_to_check.EXTEND;
            v_users_to_check(v_users_to_check.LAST) := :NEW.username;
        END IF;
    END AFTER EACH ROW;

    -- 3. AFTER STATEMENT: Process Logic & Simulate Email
    AFTER STATEMENT IS
    BEGIN
        FOR i IN 1 .. v_users_to_check.COUNT LOOP
            
            -- Count failures
            SELECT COUNT(*)
            INTO v_failed_count
            FROM login_audit
            WHERE username = v_users_to_check(i)
              AND status = 'FAILED'
              AND TRUNC(attempt_time) = TRUNC(SYSDATE);
            
            -- Check Threshold
            IF v_failed_count > v_limit THEN
                
                -- A. Insert into Security Alerts
                INSERT INTO security_alerts (
                    username, 
                    failed_count, 
                    alert_message, 
                    notify_email
                ) VALUES (
                    v_users_to_check(i),
                    v_failed_count,
                    'Threshold exceeded for user ' || v_users_to_check(i),
                    'admin@security.com'
                );

                -- B. CALL THE SIMULATED EMAIL PROCEDURE
                mock_send_email(
                    p_recipient => 'admin@security.com',
                    p_subject   => 'ALERT: Suspicious Activity Detected',
                    p_message   => 'User ' || v_users_to_check(i) || 
                                   ' has failed ' || v_failed_count || ' times today.'
                );
                
            END IF;
        END LOOP;
    END AFTER STATEMENT;

END trg_check_suspicious_login;
/

--The procedure for an email notification simulation
CREATE OR REPLACE PROCEDURE mock_send_email (
    p_recipient IN VARCHAR2,
    p_subject   IN VARCHAR2,
    p_message   IN VARCHAR2
) IS
BEGIN
    -- This simulates the email sending process
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('[SIMULATION] Sending Email...');
    DBMS_OUTPUT.PUT_LINE('TO:      ' || p_recipient);
    DBMS_OUTPUT.PUT_LINE('SUBJECT: ' || p_subject);
    DBMS_OUTPUT.PUT_LINE('BODY:    ' || p_message);
    DBMS_OUTPUT.PUT_LINE('STATUS:  Email Sent Successfully.');
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------------');
END;
/
